#!/bin/bash

if [ -z $1 ]; then
  echo "Usage: ./asm64 <object> (no extension)"
  exit
fi

if [ ! -e "$1.s" ]; then
  echo "Error, $1.s not found"
  echo "Noet, do not enter file extension"
  exit
fi

as $1.s -o $1.o
ld $1.o -o $1
